# Generated by Django 3.2.13 on 2022-11-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='photo',
            new_name='profile_img',
        ),
    ]
