# Generated by Django 3.2.13 on 2022-11-23 00:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.CharField(default='https://moviedive.s3.ap-northeast-2.amazonaws.com/4dd.png', max_length=500),
        ),
    ]
