# Generated by Django 3.2.13 on 2022-11-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.CharField(default='https://moviedive.s3.ap-northeast-2.amazonaws.com/earth.jpg', max_length=500),
        ),
    ]
