# Generated by Django 3.2.13 on 2022-11-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActorQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_img', models.ImageField(blank=True, upload_to='')),
                ('answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OXQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.BooleanField()),
            ],
        ),
    ]
