# Generated by Django 3.2.13 on 2022-11-23 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20221123_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='adult',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='original_title',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='view_cnt',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='vote_count',
        ),
    ]
