# Generated by Django 3.2.13 on 2022-11-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20221123_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='adult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='original_title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='view_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
