# Generated by Django 3.2.13 on 2022-11-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='제목없음', max_length=20),
        ),
    ]
