# Generated by Django 3.2.13 on 2022-11-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Review',
            new_name='review',
        ),
    ]
